spring.application.name=inventory
spring.mongodb.uri=mongodb+srv://food_delivery:food_delivery_password@cluster0.0mfbzbi.mongodb.net/inventorydb?retryWrites=true&w=majority&appName=Cluster0
my.test.value=hello123